- backend/yarn.lock
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/header/header.css
- frontend/src/components/header/header.js
- frontend/src/screens/edit-request/edit-request.js
- frontend/src/screens/sample.js
- frontend/yarn.lock
This PR adds navigation into the front end and a scaffold for a header bar and page route, to add structure to the repo. This PR is also used as an example of PR formatting.
Tested via localhost
> Frontend Header & Navigation Scaffolding

- frontend/package.json
- frontend/src/App.js
- frontend/src/components/Dropdown/index.css
- frontend/src/components/Dropdown/index.js
- frontend/src/components/header/header.js
- frontend/src/screens/component-showcase/component-showcase.css
- frontend/src/screens/component-showcase/component-showcase.js
-  I added two dropdown components, one built from scratch (`DropdownDefault`) and another using [react-select](https://react-select.com/home) library (`DropdownAdvanced`)
- `DropdownDefault` is fully working including state changes, just need to style the dropdown modal but I'll do that once we get it from the design team
- `DropdownAdvanced` will allow for way more functionality including multiple selections, but I'm having some issues with its state. 
- Added a page to navigation to showcase all the frontend components we build
> Dropdown component

- frontend/package.json
- frontend/src/components/TextInput/index.css
- frontend/src/components/TextInput/index.js
- frontend/src/screens/component-showcase/component-showcase.js
- frontend/yarn.lock
- Installed Ant Design library
- Created two Text Input components, both making use of Ant Design's `Input`:
- `TextInput` for single line inputs
- Able to set a character limit
- Able to display number of characters in the input
- `TextInputMultiline` for multiline inputs
- Able to set number of rows for the input box
- Box can be dragged to resize
- Both components have been added to the component display page (thank you Matthew for creating it :^))
Note: Tried to keep it as consistent as possible with prior FE component tickets, but glad to change it if requested. Also, making use of `antd`'s CSS file for the input box's style for now
> Text Input Component

- frontend/package.json
- frontend/src/App.test.js
- frontend/src/components/Dropdown/index.js
- frontend/src/components/Header/index.js
- frontend/src/components/Header/index.test.js
- frontend/src/redux/api/questionApi.js
- frontend/src/redux/saga/questionSaga.js
- frontend/src/redux/saga/test/questionSaga.test.js
- frontend/src/screens/component-showcase/component-showcase.js
- frontend/yarn.lock
This PR adds frontend testing via Jest and React testing library and saga testing structures and examples.
Resources:
- https://survivejs.com/blog/redux-saga-test-plan-interview/
- https://redux-saga-test-plan.jeremyfairbank.com/?q=expectSaga
Tested via localhost and unit tests
> Jest & Saga Tests Samples Done

- backend/.babelrc
- backend/index.js
- backend/package.json
- backend/src/controllers/questionController.js
- backend/src/models/question.js
- backend/src/routes/questionRoute.js
- backend/test/questionRoute.test.js
- backend/yarn.lock
This PR adds backend testing and sets up question-saving endpoint.
Resources:
- https://stackoverflow.com/questions/55424501/passing-request-body-to-post-using-super-test
- https://www.npmjs.com/package/babel-jest
- https://stackoverflow.com/questions/59879689/jest-syntaxerror-cannot-use-import-statement-outside-a-module
Tested via localhost and unit tests
> Save Question Endpoint Scaffold and Testing

- frontend/src/components/TextInput/index.js
- Really minor change
- Just removes all the fronted compilation warnings from Ant Design
- More about the issue [here](https://github.com/ant-design/ant-design/issues/33327)
> Fixed the 4 FE warnings caused by ant design

- frontend/public/index.html
- frontend/src/components/FormBuilder/FormTitle/index.css
- frontend/src/components/FormBuilder/FormTitle/index.js
- frontend/src/components/FormBuilder/index.css
- frontend/src/components/FormBuilder/index.js
- frontend/src/components/Header/index.css
- frontend/src/components/Header/index.test.js
- frontend/src/constants.js
- frontend/src/index.css
- frontend/src/screens/edit-request/edit-request.js
- frontend/src/screens/edit-request/index.css
Setup Frontend for Empty View Render
> Form Builder Empty View Render

- frontend/src/components/Card/index.css
- frontend/src/components/Card/index.js
- frontend/src/components/Dropdown/index.css
- frontend/src/components/Dropdown/index.js
- frontend/src/components/Header/index.css
- frontend/src/components/TextInput/index.css
- frontend/src/components/TextInput/index.js
- frontend/src/index.css
- frontend/src/screens/component-showcase/component-showcase.css
- frontend/src/screens/component-showcase/component-showcase.js
- Built a card component and refactored the Dropdown and TextInput components to use them
- Built another card component using Antd's Card
- updated components page to new styling with left navigation header
- Made the navigation header sticky to the top left of the screen
- Added the card components to the components screen
> Refactor out card component

- backend/src/models/question.js
- database/dummy/workflow1.sql
- database/init/organizations.sql
- database/init/questions_answer.sql
- database/init/questions_cost.sql
- database/procedures/delete-questions
- database/save-questions.sql
1. Updated Answer & Cost Tables Foreign Key with Delete Cascade
- Deleting the primary key of a question, deletes the child and any foreign keys linked to it
2. Delete Stored Procedures for all Tables
3. Save Stored Procedures for organizations, conditions
4. Updated save_cost stored procedure to match the table schema
> DD-Feature/Updated Stored Procedure + Tables

- frontend/src/redux/actions/formActions.js
- frontend/src/redux/reducers/formReducer.js
- frontend/src/redux/reducers/index.js
- Created new reducer to add the form's questions and users's chosen answers
- Added reducer to the root reducer
- Need to be tested once customer facing components are completed
> Redux Global State for All Customer Responses

- frontend/src/screens/request-form/request-form.css
- frontend/src/screens/request-form/request-form.js
- For the  user-facing  request form, calculate the  percentage of the page that has been scrolled and display  a fixed progress bar at top of the page
> simple progress bar

- backend/src/controllers/costCentreController.js
- backend/src/models/costCentre.js
- backend/src/routes/costCentreRoute.js
Cost Management Centers Endpoints completed on stakeholder request.
> Cost management backend

- backend/src/controllers/taskController.js
- backend/src/models/task.js
- backend/src/routes/taskRoute.js
- database/procedures/ticketManagement/loadProcedures.sql
- database/procedures/ticketManagement/saveProcedures.sql
- frontend/src/redux/api/ticketApi.js
Function and database that retrieves subtasks when given a task ID
Function that adds a subtask when given a task ID
Function to edit subtask status
> add/edit Subtasks in detail

- frontend/src/components/TicketBoard/index.js
Ticket board searchbar should now be implemented
> Ticket board search bar implementation

- backend/src/controllers/costCentreController.js
- backend/src/models/costCentre.js
- database/dummy/workflow1.sql
- database/init/cost_centers.sql
- database/procedures/costCenterProc.sql
Added backend and database implementation for Cost Center Table Unit Field
- Modified Cost Center Controller and Model 
- Modified Cost Center Proc and Init db files
- Modified the dummy data to include the Unit field
> Added backend and database implementation for Cost Center Table Unit Field

- frontend/src/screens/request-form/after-submission/form-progress.css
- frontend/src/screens/request-form/after-submission/form-progress.js
- Added new service request forms to the user-facing progress page to match the current design on Figma
> Update progress page to match Figma design

- frontend/src/components/FormBuilder/index.css
- frontend/src/components/TicketBoard/index.css
- frontend/src/components/TicketBoard/index.js
Changed the button position and added the assignees title. Need to add a close button but will discuss at meeting
> Moved the preview button

- database/init/questions.sql
- database/init/questions_answer.sql
- database/procedures/formCreator/save-questions.sql
- database/procedures/questionsProc.sql
> Bug fix: Fix character limits on questions

- backend/src/controllers/questionController.js
- backend/src/models/question.js
- database/procedures/questionsProc.sql
- frontend/src/components/TextAnswer/TextAnswerEditor/index.css
- frontend/src/components/TextAnswer/TextAnswerEditor/index.js
- frontend/src/components/TextAnswer/index.css
- frontend/src/components/TextAnswer/index.js
- frontend/src/constants.js
- frontend/src/redux/api/questionApi.js
- frontend/src/redux/reducers/formReducer.js
See demo for feature and changes!
**Backend/Database Updates**
1. Question table now contains an additional column called quantity that can be used to keep track # of questions input such as the textbox
2. Updated backend stored proc, routes, controllers, and models to accommodate this
**Frontend Updates**
1. Reducer for responses now has multiple responses for one individual text box question. I could not handle this on the front end concatenating multiple textbox components input into one and sending it to the database. Unsure if this is the best way to approach it, will discuss at this week's meeting! 
https://user-images.githubusercontent.com/62964506/227697650-a6f1cadc-fbd2-44d8-8e02-3dff8d816654.mov
> Multiple Text Answers - PR

- backend/src/controllers/questionController.js
- backend/src/models/question.js
- database/procedures/questionsProc.sql
- frontend/src/components/TextAnswer/TextAnswerEditor/index.css
- frontend/src/components/TextAnswer/TextAnswerEditor/index.js
- frontend/src/components/TextAnswer/index.css
- frontend/src/components/TextAnswer/index.js
- frontend/src/redux/api/questionApi.js
- frontend/src/redux/reducers/formReducer.js
> Revert "Multiple Text Answers - PR"
